import { prepare } from './capture';
import type { CaptureTask } from './types';

/**
 * Full screenshot task list — order and phases match SCREENSHOT_PLAN.md
 */
export const CAPTURE_TASKS: CaptureTask[] = [
  // ─── Phase 1 — Guest / public ───────────────────────────────────────────────
  {
    order: 1,
    phase: 1,
    group: 'marketing',
    slug: 'home',
    authState: 'guest',
    storageState: 'guest',
    priority: 'critical',
    path: () => '/',
  },
  {
    order: 2,
    phase: 1,
    group: 'marketing',
    slug: 'home-services-dropdown',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    viewport: 'desktop',
    path: () => '/',
    prepare: prepare.openServicesDropdown,
  },
  {
    order: 3,
    phase: 1,
    group: 'marketing',
    slug: 'home-mobile-nav-drawer',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    viewport: 'mobile',
    path: () => '/',
    prepare: prepare.openMobileNav,
  },
  {
    order: 4,
    phase: 1,
    group: 'marketing',
    slug: 'home-below-fold',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/',
    prepare: prepare.scrollBelowFold,
  },
  {
    order: 5,
    phase: 1,
    group: 'marketing',
    slug: 'about',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/about/',
  },
  {
    order: 6,
    phase: 1,
    group: 'marketing',
    slug: 'contact',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/contact/',
  },
  {
    order: 7,
    phase: 1,
    group: 'marketing',
    slug: 'pricing',
    authState: 'guest',
    storageState: 'guest',
    priority: 'critical',
    path: () => '/pricing/',
  },
  {
    order: 8,
    phase: 1,
    group: 'marketing',
    slug: 'astrologers',
    authState: 'guest',
    storageState: 'guest',
    priority: 'critical',
    path: () => '/astrologers/',
  },
  {
    order: 9,
    phase: 1,
    group: 'kundli',
    slug: 'share',
    authState: 'guest',
    storageState: 'guest',
    priority: 'critical',
    path: (s) => `/services/kundli/share/${s.kundliShareToken}/`,
  },
  {
    order: 10,
    phase: 1,
    group: 'horoscope',
    slug: 'share',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: (s) => `/services/horoscope/share/${s.horoscopeShareToken}/`,
  },
  {
    order: 11,
    phase: 1,
    group: 'matchmaking',
    slug: 'share',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: (s) => `/services/matchmaking/share/${s.matchmakingShareToken}/`,
  },
  {
    order: 12,
    phase: 1,
    group: 'marketing',
    slug: 'not-found',
    authState: 'guest',
    storageState: 'guest',
    priority: 'optional',
    path: () => '/does-not-exist/',
  },
  {
    order: 13,
    phase: 1,
    group: 'authentication',
    slug: 'login',
    authState: 'guest',
    storageState: 'guest',
    priority: 'critical',
    path: () => '/auth/login/',
  },
  {
    order: 14,
    phase: 1,
    group: 'authentication',
    slug: 'login-validation-errors',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/auth/login/',
    prepare: prepare.triggerLoginValidation,
  },
  {
    order: 15,
    phase: 1,
    group: 'authentication',
    slug: 'register',
    authState: 'guest',
    storageState: 'guest',
    priority: 'critical',
    path: () => '/auth/register/',
  },
  {
    order: 16,
    phase: 1,
    group: 'authentication',
    slug: 'register-validation-errors',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/auth/register/',
    prepare: prepare.triggerRegisterValidation,
  },
  {
    order: 17,
    phase: 1,
    group: 'authentication',
    slug: 'verify-email-success',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/auth/verify-email/success/',
  },
  {
    order: 18,
    phase: 1,
    group: 'authentication',
    slug: 'verify-email-error',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/auth/verify-email/error/',
  },
  {
    order: 19,
    phase: 1,
    group: 'kundli',
    slug: 'generate-guest-login-redirect',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/services/kundli/generate/',
  },
  {
    order: 20,
    phase: 1,
    group: 'horoscope',
    slug: 'guest-login-redirect',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/services/horoscope/',
  },
  {
    order: 21,
    phase: 1,
    group: 'matchmaking',
    slug: 'guest-login-redirect',
    authState: 'guest',
    storageState: 'guest',
    priority: 'important',
    path: () => '/services/matchmaking/',
  },

  // ─── Phase 2 — User session ─────────────────────────────────────────────────
  {
    order: 22,
    phase: 2,
    group: 'marketing',
    slug: 'astrologers-authed',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: () => '/astrologers/',
  },
  {
    order: 23,
    phase: 2,
    group: 'chat',
    slug: 'astrologers-start-chat-modal',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: () => '/astrologers/',
    prepare: prepare.openAstrologersChatDialog,
  },
  {
    order: 24,
    phase: 2,
    group: 'wallet',
    slug: 'pricing-authed',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: () => '/pricing/',
  },
  {
    order: 25,
    phase: 2,
    group: 'user-dashboard',
    slug: 'basic-info-tab',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/profile/',
    prepare: prepare.clickProfileTab(/basic info/i),
  },
  {
    order: 26,
    phase: 2,
    group: 'user-dashboard',
    slug: 'kundli-profile-tab',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/profile/',
    prepare: prepare.clickProfileTab(/kundli profile/i),
  },
  {
    order: 27,
    phase: 2,
    group: 'user-dashboard',
    slug: 'password-tab',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: () => '/profile/',
    prepare: prepare.clickProfileTab(/manage password/i),
  },
  {
    order: 28,
    phase: 2,
    group: 'reports',
    slug: 'list-populated',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/reports/',
  },
  {
    order: 29,
    phase: 2,
    group: 'wallet',
    slug: 'balance-and-transactions',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/wallet/',
  },
  {
    order: 30,
    phase: 2,
    group: 'chat',
    slug: 'conversations-list',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/conversations/',
  },
  {
    order: 31,
    phase: 2,
    group: 'chat',
    slug: 'session-thread',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: (s) => `/chat/${s.chatSessionId}/`,
  },
  {
    order: 32,
    phase: 2,
    group: 'kundli',
    slug: 'generate-empty',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/services/kundli/generate/',
  },
  {
    order: 33,
    phase: 2,
    group: 'kundli',
    slug: 'generate-filled',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: () => '/services/kundli/generate/',
    prepare: prepare.fillKundliGenerateForm,
  },
  {
    order: 34,
    phase: 2,
    group: 'kundli',
    slug: 'result-summary',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: (s) => `/services/kundli/result/${s.kundliResultId}/`,
    prepare: prepare.clickKundliTab('Dashboard'),
  },
  {
    order: 35,
    phase: 2,
    group: 'kundli',
    slug: 'result-dasha',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: (s) => `/services/kundli/result/${s.kundliResultId}/`,
    prepare: prepare.clickKundliTab('Dasha'),
  },
  {
    order: 36,
    phase: 2,
    group: 'kundli',
    slug: 'result-ashtakvarga',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: (s) => `/services/kundli/result/${s.kundliResultId}/`,
    prepare: prepare.clickKundliTab('Ashtakvarga'),
  },
  {
    order: 37,
    phase: 2,
    group: 'kundli',
    slug: 'result-chart',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: (s) => `/services/kundli/result/${s.kundliResultId}/`,
    prepare: prepare.clickKundliTab('Kundli'),
  },
  {
    order: 38,
    phase: 2,
    group: 'horoscope',
    slug: 'generate',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/services/horoscope/',
  },
  {
    order: 39,
    phase: 2,
    group: 'horoscope',
    slug: 'result',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: (s) => `/services/horoscope/result/${s.horoscopeResultId}/`,
  },
  {
    order: 40,
    phase: 2,
    group: 'matchmaking',
    slug: 'step-1',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/services/matchmaking/',
  },
  {
    order: 41,
    phase: 2,
    group: 'matchmaking',
    slug: 'step-2',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: () => '/services/matchmaking/',
    prepare: prepare.matchmakingGoToStep(2),
  },
  {
    order: 42,
    phase: 2,
    group: 'matchmaking',
    slug: 'step-3',
    authState: 'user',
    storageState: 'user',
    priority: 'important',
    path: () => '/services/matchmaking/',
    prepare: prepare.matchmakingGoToStep(3),
  },
  {
    order: 43,
    phase: 2,
    group: 'matchmaking',
    slug: 'result',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: (s) => `/services/matchmaking/result/${s.matchmakingResultId}/`,
  },
  {
    order: 44,
    phase: 2,
    group: 'wallet',
    slug: 'pricing-plan-selected',
    authState: 'user',
    storageState: 'user',
    priority: 'critical',
    path: () => '/pricing/',
    prepare: prepare.selectPricingPlan,
  },

  // ─── Phase 3 — Alternate user states ────────────────────────────────────────
  {
    order: 45,
    phase: 3,
    group: 'reports',
    slug: 'list-empty',
    authState: 'new-user',
    storageState: 'new-user',
    priority: 'important',
    path: () => '/reports/',
  },
  {
    order: 46,
    phase: 3,
    group: 'chat',
    slug: 'conversations-empty',
    authState: 'new-user',
    storageState: 'new-user',
    priority: 'important',
    path: () => '/conversations/',
  },
  {
    order: 47,
    phase: 3,
    group: 'wallet',
    slug: 'low-balance',
    authState: 'low-wallet',
    storageState: 'low-wallet',
    priority: 'important',
    path: () => '/wallet/',
  },
  {
    order: 48,
    phase: 3,
    group: 'chat',
    slug: 'session-low-coins',
    authState: 'low-wallet',
    storageState: 'low-wallet',
    priority: 'important',
    path: (s) => `/chat/${s.lowBalanceChatSessionId || s.chatSessionId}/`,
    skip: (s) => !s.lowBalanceChatSessionId,
  },
  {
    order: 49,
    phase: 3,
    group: 'user-dashboard',
    slug: 'password-set-google',
    authState: 'google-user',
    storageState: 'google-user',
    priority: 'optional',
    path: () => '/profile/',
    prepare: prepare.clickProfileTab(/manage password/i),
    skip: (s) => !s.googleUserEmail || !s.googleUserPassword,
  },
  {
    order: 50,
    phase: 3,
    group: 'astrologer',
    slug: 'register-step-1',
    authState: 'applicant',
    storageState: 'applicant',
    priority: 'critical',
    path: () => '/astrologer/register/',
  },
  {
    order: 51,
    phase: 3,
    group: 'astrologer',
    slug: 'register-step-3',
    authState: 'applicant',
    storageState: 'applicant',
    priority: 'important',
    path: () => '/astrologer/register/',
    prepare: prepare.astrologerRegisterGoToStep(3),
  },
  {
    order: 52,
    phase: 3,
    group: 'astrologer',
    slug: 'register-success',
    authState: 'applicant',
    storageState: 'applicant',
    priority: 'important',
    path: () => '/astrologer/register/success/',
  },

  // ─── Phase 4 — Admin ────────────────────────────────────────────────────────
  {
    order: 53,
    phase: 4,
    group: 'admin',
    slug: 'dashboard',
    authState: 'admin',
    storageState: 'admin',
    priority: 'critical',
    path: () => '/admin/',
  },
  {
    order: 54,
    phase: 4,
    group: 'admin',
    slug: 'users',
    authState: 'admin',
    storageState: 'admin',
    priority: 'critical',
    path: () => '/admin/users/',
  },
  {
    order: 55,
    phase: 4,
    group: 'admin',
    slug: 'user-detail',
    authState: 'admin',
    storageState: 'admin',
    priority: 'important',
    path: (s) => `/admin/users/${s.adminUserId}/`,
  },
  {
    order: 56,
    phase: 4,
    group: 'admin',
    slug: 'user-edit',
    authState: 'admin',
    storageState: 'admin',
    priority: 'important',
    path: (s) => `/admin/users/${s.adminUserId}/edit/`,
  },
  {
    order: 57,
    phase: 4,
    group: 'admin',
    slug: 'astrologers',
    authState: 'admin',
    storageState: 'admin',
    priority: 'critical',
    path: () => '/admin/astrologers/',
  },
  {
    order: 58,
    phase: 4,
    group: 'admin',
    slug: 'astrologer-detail',
    authState: 'admin',
    storageState: 'admin',
    priority: 'important',
    path: (s) => `/admin/astrologers/${s.adminAstrologerId}/`,
  },
  {
    order: 59,
    phase: 4,
    group: 'admin',
    slug: 'astrologer-requests',
    authState: 'admin',
    storageState: 'admin',
    priority: 'critical',
    path: () => '/admin/astrologer-requests/',
  },
  {
    order: 60,
    phase: 4,
    group: 'admin',
    slug: 'astrologer-request-detail',
    authState: 'admin',
    storageState: 'admin',
    priority: 'important',
    path: (s) => `/admin/astrologer-requests/${s.adminRequestId}/`,
  },
  {
    order: 61,
    phase: 4,
    group: 'admin',
    slug: 'ai-astrologers',
    authState: 'admin',
    storageState: 'admin',
    priority: 'critical',
    path: () => '/admin/ai-astrologers/',
  },
  {
    order: 62,
    phase: 4,
    group: 'admin',
    slug: 'ai-astrologers-create-modal',
    authState: 'admin',
    storageState: 'admin',
    priority: 'important',
    path: () => '/admin/ai-astrologers/',
    prepare: prepare.openAdminCreateAiModal,
  },
  {
    order: 63,
    phase: 4,
    group: 'admin',
    slug: 'coins',
    authState: 'admin',
    storageState: 'admin',
    priority: 'critical',
    path: () => '/admin/coins/',
  },
  {
    order: 64,
    phase: 4,
    group: 'admin',
    slug: 'coins-plans',
    authState: 'admin',
    storageState: 'admin',
    priority: 'important',
    path: () => '/admin/coins/plans/',
  },
  {
    order: 65,
    phase: 4,
    group: 'admin',
    slug: 'kundli-support',
    authState: 'admin',
    storageState: 'admin',
    priority: 'important',
    path: () => '/admin/kundli-support/',
  },

  // ─── Phase 5 — Astrologer ───────────────────────────────────────────────────
  {
    order: 66,
    phase: 5,
    group: 'astrologer',
    slug: 'dashboard',
    authState: 'astrologer',
    storageState: 'astrologer',
    priority: 'critical',
    path: () => '/astrologer/',
  },
  {
    order: 67,
    phase: 5,
    group: 'astrologer',
    slug: 'profile',
    authState: 'astrologer',
    storageState: 'astrologer',
    priority: 'critical',
    path: () => '/astrologer/profile/',
  },
  {
    order: 68,
    phase: 5,
    group: 'astrologer',
    slug: 'services',
    authState: 'astrologer',
    storageState: 'astrologer',
    priority: 'critical',
    path: () => '/astrologer/services/',
  },
  {
    order: 69,
    phase: 5,
    group: 'astrologer',
    slug: 'settings',
    authState: 'astrologer',
    storageState: 'astrologer',
    priority: 'important',
    path: () => '/astrologer/settings/',
  },

  // ─── Phase 6 — Optional / destructive ─────────────────────────────────────
  {
    order: 70,
    phase: 6,
    group: 'authentication',
    slug: 'verify-email-loading',
    authState: 'guest',
    storageState: 'guest',
    priority: 'optional',
    path: (s) => `/auth/verify-email/?token=${encodeURIComponent(s.verifyEmailToken)}`,
    skip: (s) => !s.verifyEmailToken,
  },
  {
    order: 71,
    phase: 6,
    group: 'authentication',
    slug: 'google-callback',
    authState: 'guest',
    storageState: 'guest',
    priority: 'optional',
    path: (s) => `/auth/google/callback/?token=${encodeURIComponent(s.mockOAuthToken)}`,
    skip: (s) => !s.mockOAuthToken,
  },
  {
    order: 72,
    phase: 6,
    group: 'horoscope',
    slug: 'result-detailed',
    authState: 'user',
    storageState: 'user',
    priority: 'optional',
    path: (s) => `/services/horoscope/result/${s.horoscopeDetailedResultId}/`,
    skip: (s) => !s.horoscopeDetailedResultId,
  },
  {
    order: 73,
    phase: 6,
    group: 'marketing',
    slug: 'account-deactivated',
    authState: 'guest',
    storageState: 'guest',
    priority: 'optional',
    path: () => '/?error=account_deactivated',
  },
  {
    order: 74,
    phase: 1,
    group: 'marketing',
    slug: 'footer',
    authState: 'guest',
    storageState: 'guest',
    priority: 'optional',
    viewport: 'desktop',
    path: () => '/about/',
    prepare: prepare.scrollToFooter,
  },
];

export const ROUTE_GROUPS = [
  'marketing',
  'authentication',
  'user-dashboard',
  'kundli',
  'horoscope',
  'matchmaking',
  'chat',
  'wallet',
  'reports',
  'admin',
  'astrologer',
] as const;
